### ISSUE TITLE
Register page gives no indication it's doing anything until it's done

### ISSUE THREAD

**Issue by MrAttoAttoAtto** [bhuvan21/arx-noctis#5]
The register page changes in no visible way once the "register" button is pressed (until a response is given), and due to the slowness of the backend, this meant I mashed "Register", thinking it wasn't working. There should be some sort of loading indication and you should not be allowed to press the register button again until the registration has failed.

**Comment by bhuvan21** [comment]
Added loading indicator

**Comment by bhuvan21** [comment]
made buttons unmashable

**Comment by bhuvan21** [comment]
Recent commit removes the use of threading (as webgl doesn't like it), so there is now a bit of a delay between pressing the button to sumbit, and the activity indicator appearing and animating, as the password hashing now takes its time on the main thread
Not really sure how to solve this for now, other than reducing the pbkdf2 iteration count, but that's not ideal

**Comment by MrAttoAttoAtto** [comment]
Surely the obvious solution is to show the loading indicator (or at least disable the register button) before hashing the password?

**Comment by bhuvan21** [comment]
This is already the case - but unity freezes until the hashing is done, so the loading indicator does not animate until the hashing finishes and unity unfreezes
The bug is technically fixed in that the user can't spam the server or anything since the button becomes disabled, but that period of time where there isn't an animating loading indicator is a bit annoying

**Comment by MrAttoAttoAtto** [comment]
Isn’t the solution then to have a non-animated indicator? (Or at least, not continuously animated)

**Comment by bhuvan21** [comment]
tru
