### ISSUE TITLE
Login boxes do not allow common keyboard shortcuts

### ISSUE THREAD

**Issue by MrAttoAttoAtto** [bhuvan21/arx-noctis#8]
I am unable to paste into the login boxes, nor can I use tab to cycle between them

**Comment by bhuvan21** [comment]
the tabbing is fixed in the next commit, but the copy-pasting is a unity WebGL thing - copy-pasting is allowed if the copied text is from the game itself but not if it's from anywhere else
I'm going to count this as fixed since it doesn't look like there's much I can do about this (and I also feel like copying and pasting in login and register isn't that necessary)

**Comment by MrAttoAttoAtto** [comment]
Password managers are increasingly becoming what every security specialist recommends...
